Restaurant_Core/Controllers/DistritoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Restaurant_Core.Models;
using System.Data;
using System.Data.SqlClient;
using Microsoft.Extensions.Configuration;

namespace Restaurant_Core.Controllers
{
    public class DistritoController : Controller
    {

        private readonly IConfiguration _Iconfig;
        public DistritoController(IConfiguration Iconfig)
        {
            _Iconfig = Iconfig;
        }

        IEnumerable<DistritoModel> Distritos()
        {
            List<DistritoModel> lista = new List<DistritoModel>();
            using (SqlConnection cn = new SqlConnection(_Iconfig["ConnectionStrings:cn"]))
            {
                SqlCommand cmd = new SqlCommand("usp_DistritoListar", cn);
                cn.Open();
                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    lista.Add(new DistritoModel()
                    {
                        idDistrito = dr.GetInt32(0),
                        nomDistrito = dr.GetString(1)
                    });
                }
            }
            return lista;
        }

        public async Task<IActionResult> ListadoDistritos()
        {
            return View(await Task.Run(() => Distritos()));
        }

        DistritoModel BuscarDistrito(int id)
        {
            DistritoModel reg = Distritos().Where(c => c.idDistrito == id).FirstOrDefault();
            return reg;
        }

        public IActionResult Create()
        {
            return View(new DistritoModel());
        }

        [HttpPost]

        public IActionResult Create(DistritoModel reg)
        {
            if (!ModelState.IsValid)
            {
                return View(reg);
            }
            string mensaje = string.Empty;
            using (SqlConnection cn = new SqlConnection(_Iconfig["ConnectionStrings:cn"]))
            {
                try
                {
                    cn.Open();
                    SqlCommand cmd = new SqlCommand("usp_InsertDistrito", cn);
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@nomdistrito", reg.nomDistrito);
                    int num = cmd.ExecuteNonQuery();
                    mensaje = $"Se ha insertado {num} distrito (s)";
                }
                catch (SqlException ex)
                {
                    mensaje = ex.Message.ToString();
                }
                ViewBag.mensaje = mensaje;
                return View(reg);
            }
        }

        public IActionResult Edit(int id)
        {
            DistritoModel reg = BuscarDistrito(id);
            if (reg == null)
                return RedirectToAction("ListadoDistritos");
            return View(reg);
        }

        [HttpPost]

        public IActionResult Edit(DistritoModel reg)
        {
            if (!ModelState.IsValid)
            {
                return View(reg);
            }
            string mensaje = string.Empty;
            using (SqlConnection cn = new SqlConnection(_Iconfig["ConnectionStrings:cn"]))
            {
                try
                {
                    cn.Open();
                    SqlCommand cmd = new SqlCommand("usp_EditDistrito", cn);
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@iddistrito", reg.idDistrito);
                    cmd.Parameters.AddWithValue("@nomdistrito", reg.nomDistrito);
                    int num = cmd.ExecuteNonQuery();
                    mensaje = $"Se ha actualizado {num} distrito (s)";
                }
                catch (SqlException ex)
                {
                    mensaje = ex.Message.ToString();
                }
                ViewBag.mensaje = mensaje;
                return View(reg);
            }
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Restaurant_Core/Views/Distrito/Create.cshtml
@model Restaurant_Core.Models.DistritoModel

@{
    ViewData["Title"] = "Create";
}

<h1 class="text-center">Registro de Distritos</h1>

<h4>Distrito</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nomDistrito" class="control-label"></label>
                <input asp-for="nomDistrito" class="form-control" />
                <span asp-validation-for="nomDistrito" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a asp-action="Create" asp-controller="Distrito" class="btn btn-primary">Nuevo</a>
                <input type="submit" value="Guardar" class="btn btn-primary" />
                <a asp-action="ListadoDistritos" asp-controller="Distrito" class="btn btn-primary">Retornar</a>
            </div>
        </form>
    </div>
</div>

<div>@ViewBag.mensaje</div>

Restaurant_Core/Views/Distrito/Edit.cshtml
@model Restaurant_Core.Models.DistritoModel

@{
    ViewData["Title"] = "Edit";
}

<h1 class="text-center">Actualizacion de datos</h1>

<h4>Distrito</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="idDistrito" class="control-label"></label>
                <input asp-for="idDistrito" class="form-control" readonly/>
                <span asp-validation-for="idDistrito" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nomDistrito" class="control-label"></label>
                <input asp-for="nomDistrito" class="form-control" />
                <span asp-validation-for="nomDistrito" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Actualizar" class="btn btn-primary" />
                <a asp-action="ListadoDistritos" asp-controller="Distrito" class="btn btn-primary">Retornar</a>
            </div>
        </form>
    </div>
</div>

<div>@ViewBag.mensaje</div>

Restaurant_Core/Views/Distrito/ListadoDistritos.cshtml
@model IEnumerable<Restaurant_Core.Models.DistritoModel>

@{
    ViewData["Title"] = "ListadoDistritos";
}

<h1 class="text-center">Listado de Distritos</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Nuevo Distrito</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.idDistrito)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nomDistrito)
            </th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.idDistrito)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nomDistrito)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.idDistrito})
                @*@Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |*@
                @*@Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@
            </td>
        </tr>
}
    </tbody>
</table>