Restaurant_Core/Controllers/AccesoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Restaurant_Core.Models;
using System.Data;
using System.Data.SqlClient;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Http;
using System.Text;
using System.Security.Cryptography;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using System.Security.Claims;

namespace Restaurant_Core.Controllers
{
    public class AccesoController : Controller
    {
        private readonly IConfiguration _Iconfig;
                
        public AccesoController(IConfiguration Iconfig)
        {
            _Iconfig = Iconfig;
        }              

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]

        public async Task<IActionResult> Login(UsuarioModel objUsuario)
        {
            objUsuario.pass = ConvertirSha256(objUsuario.pass);

            using (SqlConnection cn = new SqlConnection(_Iconfig["ConnectionStrings:cn"]))
            {
                SqlCommand cmd = new SqlCommand("usp_ValidarUsuario", cn);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("username", objUsuario.username);
                cmd.Parameters.AddWithValue("pass", objUsuario.pass);

                cn.Open();

                objUsuario.id_usuario = Convert.ToInt32(cmd.ExecuteScalar().ToString());
            }
            if (objUsuario.id_usuario != 0)
            { 
                var _claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, objUsuario.username),
                    new Claim("username", objUsuario.pass)
                };

                var _claimsIdentity = new ClaimsIdentity(_claims, CookieAuthenticationDefaults.AuthenticationScheme);

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(_claimsIdentity));

                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewData["Mensaje"] = "Usuario no encontrado";
                return View();
            }
        }

        public async Task<IActionResult> Salir()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Login", "Acceso");
        }

        public static string ConvertirSha256(string texto)
        {
            StringBuilder Sb = new StringBuilder();
            using (SHA256 hash = SHA256Managed.Create())
            {
                Encoding enc = Encoding.UTF8;
                byte[] result = hash.ComputeHash(enc.GetBytes(texto));

                foreach (byte b in result)
                    Sb.Append(b.ToString("x2"));
            }
            return Sb.ToString();
        }
    }
}

Restaurant_Core/Controllers/RestaurantController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Restaurant_Core.Models;
using System.Data;
using System.Data.SqlClient;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Session;
using Microsoft.AspNetCore.Http;
using System.Text;
using System.Security.Cryptography;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Restaurant_Core.Controllers
{
    public class RestaurantController : Controller
    {
        private readonly IConfiguration _Iconfig;
                
        public RestaurantController(IConfiguration Iconfig)
        {
            _Iconfig = Iconfig;
        }              

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]      

        public IActionResult Login(UsuarioModel objUsuario)
        {
            objUsuario.pass = ConvertirSha256(objUsuario.pass);

            using (SqlConnection cn = new SqlConnection(_Iconfig["ConnectionStrings:cn"]))
            {
                SqlCommand cmd = new SqlCommand("usp_ValidarUsuario", cn);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("username", objUsuario.username);
                cmd.Parameters.AddWithValue("pass", objUsuario.pass);

                cn.Open();

                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    objUsuario.id_usuario = dr.GetInt32(0);
                    objUsuario.nom_usuario = dr.GetString(1);
                    objUsuario.ape_usuario = dr.GetString(2);
                    objUsuario.username = dr.GetString(3);
                    objUsuario.email = dr.GetString(4);
                    objUsuario.fono_user = dr.GetString(5);
                    objUsuario.id_rol = dr.GetInt32(6);
                    objUsuario.id_distrito = dr.GetInt32(7);
                    objUsuario.estado = dr.GetInt32(8);
                }
            }
            if (objUsuario.id_usuario != 0) 
            {                
                HttpContext.Session.SetString("usuario", JsonConvert.SerializeObject(objUsuario));               
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewData["Mensaje"] = "Usuario no encontrado";
                return View();
            }            
        }
        public static string ConvertirSha256(string texto)
        {
            StringBuilder Sb = new StringBuilder();
            using (SHA256 hash = SHA256Managed.Create())
            {
                Encoding enc = Encoding.UTF8;
                byte[] result = hash.ComputeHash(enc.GetBytes(texto));

                foreach (byte b in result)
                    Sb.Append(b.ToString("x2"));
            }
            return Sb.ToString();
        }
    }
}

Restaurant_Core/Views/Acceso/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <script src="https://cdn.tailwindcss.com"></script>


    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Caveat&display=swap" rel="stylesheet">

    <title>Login</title>
</head>
<body>
    <div class="bg-white dark:bg-gray-900">
    <div class="flex justify-center h-screen">
        <div class="hidden bg-cover lg:block lg:w-2/3" style="background-image: url(https://wallpaperaccess.com/full/3353916.jpg) ">
            <div class="flex items-center h-full px-20 bg-gray-900 bg-opacity-40">
                <div>
                    <h2 class="text-5xl font-bold text-white tracking-widest" style="font-family: Poppins">OrderFast</h2>

                    <p class="max-w-xl mt-3 text-white text-2xl italic" style="font-family: Caveat">Una forma más rápida de hacer tus pedidos...</p>
                </div>
            </div>
        </div>

        <div class="flex items-center w-full max-w-md px-6 mx-auto lg:w-2/6">
            <div class="flex-1">
                <div class="text-center">
                    <h2 class="text-4xl font-bold text-center text-gray-700 dark:text-white tracking-widest" style="font-family: Poppins">Orderfast</h2>
                    <p class="mt-3 text-white dark:text-gray-300" style="font-family: Poppins">Iniciar sesión</p>
                </div>

                <div class="mt-8">
                    <form action="@Url.Action("Login","Acceso")" method="post">
                        <div>
                            <label for="username" class="block mb-2 text-sm text-gray-600 dark:text-gray-200" style="font-family: Poppins">Usuario</label>
                            <input type="text" name="username" id="username" placeholder="Ingrese su usuario" class="block w-full text-sm px-4 py-2 mt-2 text-gray-700 placeholder-gray-400 bg-white border border-gray-200 rounded-md dark:placeholder-gray-600 dark:bg-gray-900 dark:text-gray-300 dark:border-gray-700 focus:border-blue-400 dark:focus:border-blue-400 focus:ring-blue-400 focus:outline-none focus:ring focus:ring-opacity-40" style="font-family: Poppins" />
                        </div>

                        <div class="mt-6">                            
                            <label for="password" class="block mb-2 text-sm text-gray-600 dark:text-gray-200" style="font-family: Poppins">Contraseña</label>                              
                            <input type="password" name="pass" id="pass" placeholder="Ingrese su contraseña" class="block w-full text-sm px-4 py-2 mt-2 text-gray-700 placeholder-gray-400 bg-white border border-gray-200 rounded-md dark:placeholder-gray-600 dark:bg-gray-900 dark:text-gray-300 dark:border-gray-700 focus:border-blue-400 dark:focus:border-blue-400 focus:ring-blue-400 focus:outline-none focus:ring focus:ring-opacity-40" style="font-family: Poppins" />
                        </div>

                        @*ALERT*@

                        @if (ViewData["Mensaje"] != null)                        { 
                           
                            <div class="alerta mt-6 rounded-xl w-full text-white bg-red-500">
                                <div class="container flex items-center justify-between px-6 py-4 mx-auto">
                                    <div class="flex">
                                        <svg viewBox="0 0 40 40" class="w-6 h-6 fill-current">
                                            <path d="M20 3.36667C10.8167 3.36667 3.3667 10.8167 3.3667 20C3.3667 29.1833 10.8167 36.6333 20 36.6333C29.1834 36.6333 36.6334 29.1833 36.6334 20C36.6334 10.8167 29.1834 3.36667 20 3.36667ZM19.1334 33.3333V22.9H13.3334L21.6667 6.66667V17.1H27.25L19.1334 33.3333Z"></path>
                                        </svg>

                                        <p class="mx-3" style="font-family: Poppins">@ViewData["Mensaje"]</p>
                                    </div>                              
                                </div>
                            </div>
                        }                        

                        <div class="mt-6">
                            <button type="submit" class="w-full px-4 py-2 tracking-wide text-white transition-colors duration-200 transform bg-blue-500 rounded-md hover:bg-blue-400 focus:outline-none focus:bg-blue-400 focus:ring focus:ring-blue-300 focus:ring-opacity-50" style="font-family: Poppins">
                                Iniciar sesión
                            </button>
                        </div>

                    </form>

                    @*<p class="mt-6 text-sm text-center text-gray-400" style="font-family: Poppins">¿No tienes una cuenta? <a href="@Url.Action("Registrar","Restaurant")" class="text-blue-500 focus:outline-none focus:underline hover:underline">Registrarse</a>.</p>*@
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>