Restaurant_Core/Controllers/MesaController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Restaurant_Core.Models;
using System.Data;
using System.Data.SqlClient;
using Microsoft.Extensions.Configuration;

namespace Restaurant_Core.Controllers
{
    public class MesaController : Controller
    {

        private readonly IConfiguration _IConfig;

        public MesaController(IConfiguration IConfig)
        {
            _IConfig = IConfig;
        }

        // Listar Mesa
        IEnumerable<MesaModel> listaMesas()
        {
            List<MesaModel> lista = new List<MesaModel>();
            SqlConnection cn = new SqlConnection(_IConfig["ConnectionStrings:cn"]);
            SqlCommand cmd = new SqlCommand("usp_listarMesa", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            try
            {
                cn.Open();
                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    MesaModel objMesa = new MesaModel()
                    {
                        idMesa = dr[0].ToString(),
                        descMesa = dr[1].ToString()
                    };
                    lista.Add(objMesa);
                }
                dr.Close();
                cn.Close();
            }
            catch (SqlException ex)
            {
                throw ex;
            }
            return lista;
        }
        public async Task<IActionResult> ListadoMesas()
        {
            return View(await Task.Run(() => listaMesas()));
        }

        // Buscar Mesa
        MesaModel BuscarMesa(string id)
        {
            MesaModel reg = listaMesas().Where(c => c.idMesa == id).FirstOrDefault();
            return reg;
        }

        // Crear Mesa
        public async Task<IActionResult> Create()
        {
            return View(new MesaModel());
        }

        [HttpPost]
        public async Task<IActionResult> Create(MesaModel reg)
        {
            if (!ModelState.IsValid)
            {
                return View(reg);
            }

            string mensaje = string.Empty;
            using (SqlConnection cn = new SqlConnection(_IConfig["ConnectionStrings:cn"]))
            {
                try
                {
                    cn.Open();
                    SqlCommand cmd = new SqlCommand("usp_Merge_Mesas", cn);
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@idmesa", reg.idMesa);
                    cmd.Parameters.AddWithValue("@descmesa", reg.descMesa);

                    int num = cmd.ExecuteNonQuery();
                    mensaje = $"¡Se agrego {num} mesa(s) correctamente!";
                }
                catch (SqlException ex)
                {
                    mensaje = ex.Message.ToString();
                }
                ViewBag.mensaje = mensaje;
                return View(reg);
            }
        }

        // Editar Mesa
        public IActionResult Edit(string id)
        {
            MesaModel reg = BuscarMesa(id);
            if (reg == null)
                return RedirectToAction("ListadoMesas");
            return View(reg);
        }

        [HttpPost]

        public IActionResult Edit(MesaModel reg)
        {
            if (!ModelState.IsValid)
            {
                return View(reg);
            }
            string mensaje = string.Empty;
            using (SqlConnection cn = new SqlConnection(_IConfig["ConnectionStrings:cn"]))
            {
                try
                {
                    cn.Open();
                    SqlCommand cmd = new SqlCommand("usp_Merge_Mesas", cn);
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@idmesa", reg.idMesa);
                    cmd.Parameters.AddWithValue("@descmesa", reg.descMesa);
                    int num = cmd.ExecuteNonQuery();
                    mensaje = $"Se ha actualizado {num} mesa (s)";
                }
                catch (SqlException ex)
                {
                    mensaje = ex.Message.ToString();
                }
                ViewBag.mensaje = mensaje;
                return View(reg);
            }
        }


        public IActionResult Index()
        {
            return View();
        }
    }
}

Restaurant_Core/Controllers/RolController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Restaurant_Core.Models;
using System.Data;
using System.Data.SqlClient;
using Microsoft.Extensions.Configuration;

namespace Restaurant_Core.Controllers
{
    public class RolController : Controller
    {

        private readonly IConfiguration _Iconfig;
        public RolController(IConfiguration Iconfig)
        {
            _Iconfig = Iconfig;
        }

        IEnumerable<RolModel> Roles()
        {
            List<RolModel> lista = new List<RolModel>();
            using (SqlConnection cn = new SqlConnection(_Iconfig["ConnectionStrings:cn"]))
            {
                SqlCommand cmd = new SqlCommand("usp_RolListar", cn);
                cn.Open();
                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    lista.Add(new RolModel()
                    {
                        idRol = dr.GetInt32(0),
                        nomRol = dr.GetString(1)
                    });
                }
            }
            return lista;
        }

        public async Task<IActionResult> ListadoRoles()
        {
            return View(await Task.Run(() => Roles()));
        }

        RolModel BuscarRol(int id)
        {
            RolModel reg = Roles().Where(c => c.idRol == id).FirstOrDefault();
            return reg;
        }

        public IActionResult Create()
        {
            return View(new RolModel());
        }

        [HttpPost]
        public IActionResult Create(RolModel reg)
        {
            if (!ModelState.IsValid)
            {
                return View(reg);
            }
            string mensaje = string.Empty;
            using (SqlConnection cn = new SqlConnection(_Iconfig["ConnectionStrings:cn"]))
            {
                try
                {
                    cn.Open();
                    SqlCommand cmd = new SqlCommand("usp_InsertRol", cn);
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@nomrol", reg.nomRol);
                    int num = cmd.ExecuteNonQuery();
                    mensaje = $"Se ha insertado {num} rol (es)";
                }
                catch (SqlException ex)
                {
                    mensaje = ex.Message.ToString();
                }
                ViewBag.mensaje = mensaje;
                return View(reg);
            }
        }

        public IActionResult Edit(int id)
        {
            RolModel reg = BuscarRol(id);
            if (reg == null)
                return RedirectToAction("ListadoRoles");
            return View(reg);
        }

        [HttpPost]
        public IActionResult Edit(RolModel reg)
        {
            if (!ModelState.IsValid)
            {
                return View(reg);
            }
            string mensaje = string.Empty;
            using (SqlConnection cn = new SqlConnection(_Iconfig["ConnectionStrings:cn"]))
            {
                try
                {
                    cn.Open();
                    SqlCommand cmd = new SqlCommand("usp_EditRol", cn);
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@idrol", reg.idRol);
                    cmd.Parameters.AddWithValue("@nomrol", reg.nomRol);
                    int num = cmd.ExecuteNonQuery();
                    mensaje = $"Se ha actualizado {num} rol (es)";
                }
                catch (SqlException ex)
                {
                    mensaje = ex.Message.ToString();
                }
                ViewBag.mensaje = mensaje;
                return View(reg);
            }
        }


        public IActionResult Index()
        {
            return View();
        }
    }
}

Restaurant_Core/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Restaurant_Core.Models;
using System.Data;
using System.Data.SqlClient;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Mvc.Rendering;

using Microsoft.AspNetCore.Authorization;

namespace Restaurant_Core.Controllers
{
    [Authorize]
    public class UsuarioController : Controller
    {

        private readonly IConfiguration _Iconfig;
        public UsuarioController(IConfiguration Iconfig)
        {
            _Iconfig = Iconfig;
        }

        /// <summary>
        /// listado de roles
        /// </summary>
        /// <returns></returns>
        IEnumerable<RolModel> Roles()
        {
            List<RolModel> lista = new List<RolModel>();
            using (SqlConnection cn = new SqlConnection(_Iconfig["ConnectionStrings:cn"]))
            {
                SqlCommand cmd = new SqlCommand("usp_RolListar", cn);
                cn.Open();
                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    lista.Add(new RolModel()
                    {
                        idRol = dr.GetInt32(0),
                        nomRol = dr.GetString(1)
                    });
                }
            }
            return lista;
        }

        /// <summary>
        /// listado de distritos
        /// </summary>
        /// <returns></returns>
        /// 

        IEnumerable<DistritoModel> Distritos()
        {
            List<DistritoModel> lista = new List<DistritoModel>();
            using (SqlConnection cn = new SqlConnection(_Iconfig["ConnectionStrings:cn"]))
            {
                SqlCommand cmd = new SqlCommand("usp_DistritoListar", cn);
                cn.Open();
                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    lista.Add(new DistritoModel()
                    {
                        idDistrito = dr.GetInt32(0),
                        nomDistrito = dr.GetString(1)
                    });
                }
            }
            return lista;
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        /// 

        IEnumerable<UsuarioModel> Usuarios()
        {
            List<UsuarioModel> lista = new List<UsuarioModel>();
            using (SqlConnection cn = new SqlConnection(_Iconfig["ConnectionStrings:cn"]))
            {
                SqlCommand cmd = new SqlCommand("usp_ListarUsuarios", cn);
                cn.Open();
                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    lista.Add(new UsuarioModel()
                    {
                        id_usuario = dr.GetInt32(0),
                        nom_usuario = dr.GetString(1),
                        ape_usuario = dr.GetString(2),
                        username = dr.GetString(3),
                        email = dr.GetString(4),
                        fono_user = dr.GetString(5),
                        id_rol = dr.GetInt32(6),
                        nom_rol = dr.GetString(7),
                        id_distrito = dr.GetInt32(8),
                        nom_distrito = dr.GetString(9)
                    });
                }
            }
            return lista;
        }

        public async Task<IActionResult> ListadoUsuarios()
        {
            return View(await Task.Run(() => Usuarios()));
        }

        UsuarioModel BuscarUsuario(int id)
        {
            UsuarioModel reg = Usuarios().Where(c => c.id_usuario == id).FirstOrDefault();
            return reg;
        }

        public async Task<IActionResult> Create()
        {
            ViewBag.roles = new SelectList(await Task.Run(() => Roles()), "idRol", "nomRol");
            ViewBag.distritos = new SelectList(await Task.Run(() => Distritos()), "idDistrito", "nomDistrito");
            return View(new UsuarioModel());
        }

        [HttpPost]
        public async Task<IActionResult> Create(UsuarioModel reg)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.roles = new SelectList(await Task.Run(() => Roles()), "idRol", "nomRol", reg.id_rol);
                ViewBag.distritos = new SelectList(await Task.Run(() => Distritos()), "idDistrito", "nomDistrito", reg.id_distrito);
                return View(reg);
            }
            string mensaje = string.Empty;
            using (SqlConnection cn = new SqlConnection(_Iconfig["ConnectionStrings:cn"]))
            {
                try
                {
                    cn.Open();
                    SqlCommand cmd = new SqlCommand("usp_RegistrarUsuario", cn);
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@nom_usuario", reg.nom_usuario);
                    cmd.Parameters.AddWithValue("@ape_usuario", reg.ape_usuario);
                    cmd.Parameters.AddWithValue("@email", reg.email);
                    cmd.Parameters.AddWithValue("@fono_user", reg.fono_user);
                    cmd.Parameters.AddWithValue("@id_rol", reg.id_rol);
                    cmd.Parameters.AddWithValue("@id_distrito", reg.id_distrito);
                    cmd.Parameters.AddWithValue("@estado", reg.estado);
                    int num = cmd.ExecuteNonQuery();
                    mensaje = $"Se ha insertado {num} usuario (s)";
                }
                catch (SqlException ex)
                {
                    mensaje = ex.Message.ToString();
                }
                ViewBag.mensaje = mensaje;
                ViewBag.roles = new SelectList(await Task.Run(() => Roles()), "idRol", "nomRol", reg.id_rol);
                ViewBag.distritos = new SelectList(await Task.Run(() => Distritos()), "idDistrito", "nomDistrito", reg.id_distrito);
                return View(reg);
            }
        }

        public async Task<IActionResult> Edit(int id)
        {
            UsuarioModel reg = BuscarUsuario(id);
            if (reg == null)
                return RedirectToAction("ListadoUsuarios");
            ViewBag.roles = new SelectList(await Task.Run(() => Roles()), "idRol", "nomRol", reg.id_rol);
            ViewBag.distritos = new SelectList(await Task.Run(() => Distritos()), "idDistrito", "nomDistrito", reg.id_distrito);
            return View(reg);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UsuarioModel reg)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.roles = new SelectList(await Task.Run(() => Roles()), "idRol", "nomRol", reg.id_rol);
                ViewBag.distritos = new SelectList(await Task.Run(() => Distritos()), "idDistrito", "nomDistrito", reg.id_distrito);
                return View(reg);
            }
            string mensaje = string.Empty;
            using (SqlConnection cn = new SqlConnection(_Iconfig["ConnectionStrings:cn"]))
            {
                try
                {
                    cn.Open();
                    SqlCommand cmd = new SqlCommand("usp_ActualizarUsuario", cn);
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@idusuario", reg.id_usuario);
                    cmd.Parameters.AddWithValue("@nom_usuario", reg.nom_usuario);
                    cmd.Parameters.AddWithValue("@ape_usuario", reg.ape_usuario);
                    cmd.Parameters.AddWithValue("@email", reg.email);
                    cmd.Parameters.AddWithValue("@fono_user", reg.fono_user);
                    cmd.Parameters.AddWithValue("@id_rol", reg.id_rol);
                    cmd.Parameters.AddWithValue("@id_distrito", reg.id_distrito);
                    cmd.Parameters.AddWithValue("@estado", reg.estado);
                    int num = cmd.ExecuteNonQuery();
                    mensaje = $"Se ha actualizado {num} usuario (s)";
                }
                catch (SqlException ex)
                {
                    mensaje = ex.Message.ToString();
                }
                ViewBag.mensaje = mensaje;
                ViewBag.roles = new SelectList(await Task.Run(() => Roles()), "idRol", "nomRol", reg.id_rol);
                ViewBag.distritos = new SelectList(await Task.Run(() => Distritos()), "idDistrito", "nomDistrito", reg.id_distrito);
                return View(reg);
            }
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Restaurant_Core/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Restaurant_Core</title>
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/css/stilos_main.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

</head>
<body>
    <div class="wrapper d-flex align-items-stretch">
        <nav id="sidebar">
            <div class="p-4 pt-5">
                <ul class="list-unstyled components mb-5">
                    <li class="">
                        <a asp-area="" asp-controller="Home" asp-action="Index">Dashboard</a>
                    </li>
                    <li>
                        <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Mantenimiento</a>
                        <ul class="collapse list-unstyled" id="homeSubmenu">
                            <li><a asp-area="" asp-controller="Usuario" asp-action="ListadoUsuarios">Usuarios</a></li>
                            <li><a asp-area="" asp-controller="Producto" asp-action="ListadoProductos">Productos</a></li>
                            <li><a asp-area="" asp-controller="Rol" asp-action="ListadoRoles">Roles</a></li>
                            <li><a asp-area="" asp-controller="Distrito" asp-action="ListadoDistritos">Distritos</a></li>
                            <li><a asp-area="" asp-controller="Categoria" asp-action="ListadoCategorias">Categorias</a></li>
                            <li><a asp-area="" asp-controller="Mesa" asp-action="ListadoMesas">Mesas</a></li>
                        </ul>
                    </li>
                    <li><a href="#">Pedido</a></li>
                    <li><a href="#">Configuraci&oacute;n</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">Acerca de</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contacto</a></li>
                </ul>
                <div class="footer">
                    <p>Copyright &copy; @DateTime.Now.Year All rights reserved</p>
                </div>
            </div>
        </nav>
        <!-- Page Content  -->
        <div id="content" class="p-4 p-md-5">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">
                    <button type="button" id="sidebarCollapse" class="btn btn-primary">
                        <i class="fa fa-bars"></i>
                        <span class="sr-only">Toggle Menu</span>
                    </button>
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fa fa-bars"></i>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav navbar-nav ml-auto">
                            <li class="nav-item active">
                                @*<a class="nav-link" href="#">Cerrar sesi&oacute;n</a>*@
                                <a class="nav-link" asp-area="" asp-controller="Acceso" asp-action="Salir">Cerrar sesión</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            @RenderBody()
        </div>
    </div>





    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/main.js"></script>
    <script src="~/js/popper.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>