Restaurant_Core/Controllers/CategoriaController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Restaurant_Core.Models;
using System.Data;
using System.Data.SqlClient;
using Microsoft.Extensions.Configuration;

namespace Restaurant_Core.Controllers
{
    public class CategoriaController : Controller
    {

        private readonly IConfiguration _IConfig;

        public CategoriaController(IConfiguration IConfig)
        {
            _IConfig = IConfig;
        }

        // Listar Categoria
        IEnumerable<CategoriaModel> listaCategorias()
        {
            List<CategoriaModel> lista = new List<CategoriaModel>();
            SqlConnection cn = new SqlConnection(_IConfig["ConnectionStrings:cn"]);
            SqlCommand cmd = new SqlCommand("usp_listarCategoria", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            try
            {
                cn.Open();
                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    CategoriaModel objCategoria = new CategoriaModel()
                    {
                        idCategoria = dr[0].ToString(),
                        nomCategoria = dr[1].ToString()
                    };
                    lista.Add(objCategoria);
                }
                dr.Close();
                cn.Close();
            }
            catch (SqlException ex)
            {
                throw ex;
            }
            return lista;
        }
        public async Task<IActionResult> ListadoCategorias()
        {
            return View(await Task.Run(() => listaCategorias()));
        }

        // Buscar Categoria
        CategoriaModel BuscarCategoria(string id)
        {
            CategoriaModel reg = listaCategorias().Where(c => c.idCategoria == id).FirstOrDefault();
            return reg;
        }

        // Crear Categoria
        public async Task<IActionResult> Create()
        {
            return View(new CategoriaModel());
        }

        [HttpPost]
        public async Task<IActionResult> Create(CategoriaModel reg)
        {
            if (!ModelState.IsValid)
            {
                return View(reg);
            }

            string mensaje = string.Empty;
            using (SqlConnection cn = new SqlConnection(_IConfig["ConnectionStrings:cn"]))
            {
                try
                {
                    cn.Open();
                    SqlCommand cmd = new SqlCommand("usp_Merge_Categoria", cn);
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@idcategoria", reg.idCategoria);
                    cmd.Parameters.AddWithValue("@nomcategoria", reg.nomCategoria);

                    int num = cmd.ExecuteNonQuery();
                    mensaje = $"¡Se agrego {num} categoria(s) correctamente!";
                }
                catch (SqlException ex)
                {
                    mensaje = ex.Message.ToString();
                }
                ViewBag.mensaje = mensaje;
                return View(reg);
            }
        }

        // Editar Categoria
        public IActionResult Edit(string id)
        {
            CategoriaModel reg = BuscarCategoria(id);
            if (reg == null)
                return RedirectToAction("ListadoCategorias");
            return View(reg);
        }

        [HttpPost]

        public IActionResult Edit(CategoriaModel reg)
        {
            if (!ModelState.IsValid)
            {
                return View(reg);
            }
            string mensaje = string.Empty;
            using (SqlConnection cn = new SqlConnection(_IConfig["ConnectionStrings:cn"]))
            {
                try
                {
                    cn.Open();
                    SqlCommand cmd = new SqlCommand("usp_Merge_Categoria", cn);
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@idcategoria", reg.idCategoria);
                    cmd.Parameters.AddWithValue("@nomcategoria", reg.nomCategoria);
                    int num = cmd.ExecuteNonQuery();
                    mensaje = $"Se ha actualizado {num} categoria (s)";
                }
                catch (SqlException ex)
                {
                    mensaje = ex.Message.ToString();
                }
                ViewBag.mensaje = mensaje;
                return View(reg);
            }
        }


        public IActionResult Index()
        {
            return View();
        }
    }
}

Restaurant_Core/Views/Categoria/Create.cshtml
@model Restaurant_Core.Models.CategoriaModel

@{
    ViewData["Title"] = "Create";
}

<h1 class="text-center">Módulo Categorias</h1>
<h4 class="text-center">Agregar Categorias</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="idCategoria" class="control-label"></label>
                <input asp-for="idCategoria" class="form-control" />
                <span asp-validation-for="idCategoria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nomCategoria" class="control-label"></label>
                <input asp-for="nomCategoria" class="form-control" />
                <span asp-validation-for="nomCategoria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a asp-action="Create" asp-controller="Categoria" class="btn btn-primary">Nueva</a>
                <input type="submit" value="Guardar Categoria" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ListadoCategorias" class="btn btn-primary">Regresar al Listado</a>
</div>
<div>@ViewBag.mensaje</div>

Restaurant_Core/Views/Categoria/Edit.cshtml
@model Restaurant_Core.Models.CategoriaModel

@{
    ViewData["Title"] = "Edit";
}

<h1 class="text-center">Módulo Categorias</h1>
<h4 class="text-center">Editar Categorias</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="idCategoria" class="control-label"></label>
                <input asp-for="idCategoria" class="form-control" />
                <span asp-validation-for="idCategoria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nomCategoria" class="control-label"></label>
                <input asp-for="nomCategoria" class="form-control" />
                <span asp-validation-for="nomCategoria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Actualizar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ListadoCategorias" class="btn btn-primary">Regresar al Listado</a>
</div>
<div>@ViewBag.mensaje</div>

Restaurant_Core/Views/Categoria/ListadoCategorias.cshtml
@model IEnumerable<Restaurant_Core.Models.CategoriaModel>

@{
    ViewData["Title"] = "ListadoCategorias";
}

<h1 class="text-center">Módulo de Categorias</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Nueva Categoría</a>
</p>
<table class="table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.idCategoria)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nomCategoria)
            </th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.idCategoria)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nomCategoria)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.idCategoria })
                @*@Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |*@
                @*@Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@
            </td>
        </tr>
}
    </tbody>
</table>